apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    foo: Service
  annotations:
    bar: Service
spec:
  type: ClusterIP # This is the default value
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 80 # Port the container is listening on (if unset, defaults to equal port value)